### PR TITLE
Add Stylelint v15 support

### LINKED ISSUE #86: Support Stylelint 15
Similar to https://github.com/cahamilton/stylelint-config-property-sort-order-smacss/issues/17

### PR DESCRIPTION
**Pull request by Th3S4mur41**
closes #86

### CODE REVIEW

**Comment by erwanjugand** [comment]
@Th3S4mur41 Maybe update `stylelint-order` to [6.0.2](https://github.com/hudochenkov/stylelint-order/releases/tag/6.0.2) :)

**Comment by Th3S4mur41** [comment]
@erwanjugand updated as requested 😉

**Review by cahamilton — CHANGES_REQUESTED** [review]
Hey @Th3S4mur41 - thanks for the contribution!

Would you be able to use the following commit as a template of adding support for Stylelint v15 please? https://github.com/cahamilton/stylelint-config-property-sort-order-smacss/commit/2aa5ad201f85216cffbdbd41eddfa5f581150917

This PR introduces a breaking change by removing v14 support and I'd rather not release a major version of the package.

Could we look at dropping [5bcd12b](https://github.com/cahamilton/stylelint-config-property-sort-order-smacss/pull/87/commits/5bcd12bf3b931cd039e90b4b8d9f11853599285b) from this change as well? This is covered in #85 and I'd prefer to introduce these changes separately.

**Comment by Th3S4mur41** [comment]
@cahamilton thanks for the helpful example 👍 
Changes committed as requested

**Review by cahamilton — APPROVED** [review]
Changes LGTM 👍! Thanks for contributing @Th3S4mur41.

I'll get this merged and a new minor version published to NPM soon

**Comment by cahamilton** [comment]
v9.1.0 has been published to NPM. Any problems - feel free to raise an issue.

Thanks again, much appreciated 👍

**Pull request merged**
